INSERT INTO TB_CATEGORY (NAME, created_AT) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME, created_AT) VALUES('Eletronics', NOW());
INSERT INTO TB_CATEGORY (NAME, created_AT) VALUES('Computers', NOW());